fix: Remove invalid pythonSupport parameter from AFL++ override
The AFL++ package in nixpkgs doesn't accept the pythonSupport parameter,
causing 'nix develop' to fail with an error. Removed this parameter while
keeping the LLVM 18 override which is valid and necessary.

This fixes the error:
  error: function 'anonymous lambda' called with unexpected argument 'pythonSupport'